import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { requireActiveUser } from "./lib/auth";

const preferenceV = v.union(v.object({ discipline: v.string(), qualification: v.string() }), v.null());
const docV = v.object({ id: v.id("examArchiveDocuments"), kind: v.union(v.literal("question-booklet"), v.literal("answer-key"), v.literal("descriptive-guide")), title: v.string(), discipline: v.string(), qualification: v.optional(v.string()), sourceUrl: v.string() });
async function scope(ctx: Parameters<Parameters<typeof query>[0]["handler"]>[0]) { const user = await requireActiveUser(ctx); const [preference, subscription] = await Promise.all([ctx.db.query("userExamPreferences").withIndex("by_userId",q=>q.eq("userId",user._id)).unique(),ctx.db.query("subscriptions").withIndex("by_userId",q=>q.eq("userId",user._id)).unique()]); return { user, preference, access: user.role==="admin" || (subscription?.plan==="premium" && (subscription.status==="active"||subscription.status==="trialing")) }; }
export const getPreference=query({args:{},returns:preferenceV,handler:async ctx=>{const {preference}=await scope(ctx);return preference?{discipline:preference.discipline,qualification:preference.qualification}:null;}});
export const savePreference=mutation({args:{discipline:v.string(),qualification:v.string()},returns:preferenceV,handler:async(ctx,args)=>{const user=await requireActiveUser(ctx),discipline=args.discipline.trim(),qualification=args.qualification.trim();if(!discipline||!qualification||discipline.length>80||qualification.length>80)throw new Error("INVALID_EXAM_PREFERENCE");const row=await ctx.db.query("userExamPreferences").withIndex("by_userId",q=>q.eq("userId",user._id)).unique(),now=Date.now();if(row)await ctx.db.patch(row._id,{discipline,qualification,updatedAt:now});else await ctx.db.insert("userExamPreferences",{userId:user._id,discipline,qualification,updatedAt:now});return{discipline,qualification};}});
export const listMyEligibleArchive=query({args:{},returns:v.object({hasPremiumAccess:v.boolean(),preference:preferenceV,archives:v.array(v.object({id:v.id("examArchives"),title:v.string(),officialPageUrl:v.string(),documents:v.array(docV)}))}),handler:async ctx=>{const {preference,access}=await scope(ctx),p=preference?{discipline:preference.discipline,qualification:preference.qualification}:null;if(!access||!preference)return{hasPremiumAccess:access,preference:p,archives:[]};const archives=await ctx.db.query("examArchives").withIndex("by_status_and_lastVerifiedAt",q=>q.eq("status","verified")).order("desc").take(24);const items=await Promise.all(archives.map(async a=>{const d=(await ctx.db.query("examArchiveDocuments").withIndex("by_archiveId_and_discipline",q=>q.eq("archiveId",a._id).eq("discipline",preference.discipline)).take(100)).filter(x=>x.qualification===preference.qualification||x.qualification===undefined);return{id:a._id,title:a.title,officialPageUrl:a.officialPageUrl,documents:d.map(x=>({id:x._id,kind:x.kind,title:x.title,discipline:x.discipline,qualification:x.qualification,sourceUrl:x.sourceUrl}))};}));return{hasPremiumAccess:access,preference:p,archives:items.filter(x=>x.documents.length>0)};}});
export const recentQuestionsForTopic=query({args:{topicCode:v.number()},returns:v.object({hasPremiumAccess:v.boolean(),preference:preferenceV,questions:v.array(v.object({id:v.id("examQuestionReferences"),questionNumber:v.number(),topicTitle:v.string(),sourcePage:v.optional(v.number()),sourceExcerpt:v.optional(v.string())}))}),handler:async(ctx,args)=>{if(!Number.isInteger(args.topicCode)||args.topicCode<1||args.topicCode>99)throw new Error("INVALID_TOPIC_CODE");const {preference,access}=await scope(ctx),p=preference?{discipline:preference.discipline,qualification:preference.qualification}:null;if(!access||!preference)return{hasPremiumAccess:access,preference:p,questions:[]};const rows=await ctx.db.query("examQuestionReferences").withIndex("by_topicCode_and_discipline",q=>q.eq("topicCode",args.topicCode).eq("discipline",preference.discipline)).order("desc").take(30);return{hasPremiumAccess:access,preference:p,questions:rows.map(x=>({id:x._id,questionNumber:x.questionNumber,topicTitle:x.topicTitle,sourcePage:x.sourcePage,sourceExcerpt:x.sourceExcerpt}))};}});
